apiVersion: v2
name: deep-researcher-web
description: Deep Researcher Agent - WEB Profile ()
type: application
version: 2.2.0
appVersion: '2.2.0'
dependencies:
- name: deep-researcher
  version: 0.0.5
  repository: file://../helm-charts-k8s/deep-researcher
  alias: deep-researcher
